name: Release-plz

permissions:
  pull-requests: write
  contents: write
  id-token: write # Required for trusted publishing

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Polymarket' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: '1.88'

      - name: Run release-plz
        uses: release-plz/action@064f4d1e36c843611ddf013be726beaa4ad804db # v0.5.129
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
